"""
Django settings for preciousLife project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from decouple import config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9w81kc&3z%%p&b2_e)ztnk@0!_1u67&fu9aod$((elt77189i%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    'taggit',
    'hitcount',
    'guardian',
    'notifications',
    'captcha',
    'django_summernote',

    # my personal app
    'accounts', 
    'questions_answer',
    'notice',
    'blog',
]

# captcha settings
RECAPTCHA_PUBLIC_KEY = '6Lcm_MAZAAAAAIl-stUcVO1DusGCNWtWlp1NmGlO'
RECAPTCHA_PRIVATE_KEY = '6Lcm_MAZAAAAALlIvwJIHsYM4ksBTSZIHhbvdq0O'

# django-guardian
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend',
)

# notifications settings
DJANGO_NOTIFICATIONS_CONFIG = { 
    'SOFT_DELETE': True,

}

GUARDIAN_RAISE_403 = True


# hitcount limit per ip address
# default value = 0, unlimited
HITCOUNT_HITS_PER_IP_LIMIT = 0

# sumernote settings

X_FRAME_OPTIONS = 'SAMEORIGIN'

SUMMERNOTE_CONFIG = {
    'iframe': True,


    'summernote':{

        'airMode': False,

        # Change editor size
        'width': '100%',
        'height': '480',

            'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['fontsize', ['fontsize']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture','video','hr',]],
            ['view', ['fullscreen', 'codeview','undo', 'redo']],
        ],

         'popover':
        {
        
            'image':
            [
                ['image', ['resizeHalf', 'resizeQuarter']],
                ['float', ['floatRight', 'floatNone']],
                ['remove', ['removeMedia']]

            ],

            'link': [
                ['link', ['linkDialogShow', 'unlink']]
            ],
        },

        'fontNames': ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New',],

        'fontSizeUnits': ['px', 'pt']
        
    },

}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "https://rekyndll.com",
    "http://localhost:8080",
    "http://127.0.0.1:9000"
]

ROOT_URLCONF = 'preciousLife.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'preciousLife.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'QuestionAnswer',
        'USER': 'postgres',
        'PASSWORD': 'Pugnac@scylla1310',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    'querstion_and_answer/preciousLife/accounts/static',
]

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

GOOGLE_RECAPTCHA_SECRET_KEY = '6Lc7-cAZAAAAAMXc-fjq31u1ON_3a6swLbXdK0Dy'

EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY = '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'


# Toggle sandbox mode (when running in DEBUG mode)
SENDGRID_SANDBOX_MODE_IN_DEBUG=True

# echo to stdout or any other file-like object that is passed to the backend via the stream kwarg.
SENDGRID_ECHO_TO_STDOUT=True
