# Generated by Django 3.0.8 on 2020-09-06 03:25

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0004_auto_20200906_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_taggedblog_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Give tags to the blog', related_name='blog_tags', through='blog.TaggedBlog', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
