# Generated by Django 3.0.8 on 2020-09-25 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_customattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblogpost',
            name='comment_like',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
