# Generated by Django 3.0.8 on 2020-08-31 08:25

from django.db import migrations, models
import questions_answer.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_first',
            field=models.ImageField(blank=True, null=True, upload_to='question_images', validators=[questions_answer.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_second',
            field=models.ImageField(blank=True, null=True, upload_to='question_images', validators=[questions_answer.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_third',
            field=models.ImageField(blank=True, null=True, upload_to='question_images', validators=[questions_answer.models.validate_file_size]),
        ),
    ]
