# Generated by Django 3.0.8 on 2020-08-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
