# Generated by Django 3.0.8 on 2020-07-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answer', '0002_auto_20200716_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='User',
            new_name='user',
        ),
    ]
