# Generated by Django 3.0.8 on 2020-07-17 07:29

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answer', '0003_auto_20200716_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
