# Generated by Django 3.0.8 on 2020-09-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answer', '0003_auto_20200902_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportanswer',
            name='report_description',
            field=models.TextField(max_length=264),
        ),
        migrations.AlterField(
            model_name='reportquestion',
            name='report_description',
            field=models.TextField(max_length=264),
        ),
    ]
