# Generated by Django 3.0.8 on 2020-08-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answer', '0003_reportquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportquestion',
            name='question_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
