# Generated by Django 3.0.8 on 2020-08-19 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions_answer', '0004_reportquestion_question_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_description', models.TextField(blank=True, max_length=264, null=True)),
                ('question_url', models.URLField(blank=True, null=True)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_answer.Answer')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_answer.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
