# Generated by Django 3.0.8 on 2020-09-24 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions_answer', '0004_auto_20200908_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_likes',
            field=models.ManyToManyField(blank=True, related_name='answer_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
