# Generated by Django 3.0.8 on 2020-07-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answer', '0008_auto_20200718_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
