# Generated by Django 3.0.8 on 2020-07-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answer', '0009_auto_20200718_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
