# Generated by Django 3.0.8 on 2020-07-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answer', '0011_question_profile_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='profile_detail',
        ),
    ]
