# Generated by Django 3.0.8 on 2020-08-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answer', '0017_auto_20200801_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='questions',
        ),
    ]
