# Generated by Django 3.0.8 on 2020-08-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answer', '0021_auto_20200815_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_answer.Question'),
        ),
    ]
