# Generated by Django 3.0.8 on 2020-08-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answer', '0022_auto_20200815_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_first',
            field=models.ImageField(blank=True, null=True, upload_to='question_images'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_second',
            field=models.ImageField(blank=True, null=True, upload_to='question_images'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_third',
            field=models.ImageField(blank=True, null=True, upload_to='question_images'),
        ),
    ]
