# Generated by Django 3.0.8 on 2020-07-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200719_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'others')], default='', max_length=100),
        ),
    ]
