# Generated by Django 3.0.8 on 2020-07-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofileinfo_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='website_instagram',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='website_twitter',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
