# Generated by Django 3.0.8 on 2020-09-01 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200901_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='', regex='(?P<email>[A-z0-9_.+-]+@[A-z0-9_.-]+\\.[A-z]+)')]),
        ),
    ]
