# Generated by Django 3.0.8 on 2020-07-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200721_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
    ]
