# Generated by Django 3.0.8 on 2020-08-25 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200723_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='website_instagram',
            field=models.URLField(blank=True, default='', null=True, validators=[django.core.validators.RegexValidator(message='Not a valid URL', regex='/^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$/')]),
        ),
    ]
