# Generated by Django 3.0.8 on 2020-08-25 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200825_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='website_instagram',
            field=models.URLField(blank=True, default='', null=True, validators=[django.core.validators.RegexValidator(message='', regex='(?:https?:)?\\/\\/(?:www\\.)?(?:instagram\\.com|instagr\\.am)\\/(?P<username>[A-Za-z0-9_](?:(?:[A-Za-z0-9_]|(?:\\.(?!\\.))){0,28}(?:[A-Za-z0-9_]))?)')]),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='website_twitter',
            field=models.URLField(blank=True, default='', null=True, validators=[django.core.validators.RegexValidator(message='', regex='(?:https?:)?\\/\\/(?:[A-z]+\\.)?twitter\\.com\\/@?(?P<username>[A-z0-9_]+)\\/?')]),
        ),
    ]
